"""initial schema

Revision ID: 5ea8adf60cba
Revises: 
Create Date: 2026-07-17 22:56:54.537040

"""
import sqlalchemy as sa
from alembic import op

revision = '5ea8adf60cba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_codes_email'), ['email'], unique=False)

    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipients_email'), ['email'], unique=True)

    op.create_table('recipient_sessions',
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('token')
    )

    op.create_table('recipient_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipient_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_versions_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('mailpieces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mailing_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_version_id', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.ForeignKeyConstraint(['recipient_version_id'], ['recipient_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailing_id', 'recipient_id')
    )
    with op.batch_alter_table('mailpieces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailpieces_mailing_id'), ['mailing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mailpieces_recipient_id'), ['recipient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailpieces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailpieces_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_mailpieces_mailing_id'))

    op.drop_table('mailpieces')
    with op.batch_alter_table('recipient_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_versions_recipient_id'))

    op.drop_table('recipient_versions')
    op.drop_table('recipient_sessions')
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_email'))

    op.drop_table('recipients')
    op.drop_table('mailings')
    op.drop_table('admin_sessions')
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_codes_email'))

    op.drop_table('login_codes')
    # ### end Alembic commands ###
